DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS banks;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS countries;