name: ci-test

on:
  push:
    branches: [ "1.0.0.0" ]
  pull_request:
    branches: [ "1.0.0.0" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_DB: bank_mvp
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Test
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
